import type {
  Asset,
  MediaGenerationJob,
  MediaJobInput,
  MediaJobKind,
  MediaJobStatus,
  MediaProvider,
} from "@/lib/types";

function makeId(prefix: string) {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return `${prefix}-${crypto.randomUUID()}`;
  }
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

function buildResultAsset(job: MediaGenerationJob): Asset {
  return {
    id: `generated-${job.id}`,
    kind: job.kind === "image-to-video" ? "generated-video" : "generated-image",
    label:
      job.kind === "image-to-video"
        ? "IMG2VID · Mock render"
        : "IMG2IMG · Mock render",
    title:
      job.kind === "image-to-video"
        ? "Mock motion cut"
        : "Mock editorial restyle",
    tone: job.kind === "image-to-video" ? "dark" : "warm",
    caption: `Generated by ${job.provider} for ${job.stopId}.`,
    notes: job.prompt,
  };
}

function buildJob(kind: MediaJobKind, input: MediaJobInput): MediaGenerationJob {
  const now = new Date().toISOString();
  const etaMs = kind === "image-to-video" ? 24000 : 7000;
  return {
    id: makeId("job"),
    projectId: input.projectId,
    stopId: input.stopId,
    sourceAssetId: input.sourceAssetId,
    kind,
    state: "queued",
    prompt:
      input.prompt ??
      (kind === "image-to-video"
        ? "animate a subtle cinematic move over the selected frame"
        : "restyle the selected frame to match the current narrative mode"),
    strength: input.strength ?? 0.68,
    seed: input.seed ?? Math.floor(Math.random() * 999999),
    progress: 0,
    etaMs,
    createdAt: now,
    updatedAt: now,
    provider: "mock-media-provider",
  };
}

export class MockMediaProvider implements MediaProvider {
  readonly name = "mock-media-provider";

  async createImageToImageJob(input: MediaJobInput) {
    return buildJob("image-to-image", input);
  }

  async createImageToVideoJob(input: MediaJobInput) {
    return buildJob("image-to-video", input);
  }

  async getJobStatus(job: MediaGenerationJob): Promise<MediaJobStatus> {
    if (job.state === "done" || job.state === "failed" || job.state === "cancelled") {
      return {
        job,
        resultAsset: job.resultAssetId ? undefined : buildResultAsset(job),
      };
    }

    const elapsed = Date.now() - new Date(job.createdAt).getTime();
    const total = job.kind === "image-to-video" ? 24000 : 7000;
    const progress = Math.max(5, Math.min(100, Math.round((elapsed / total) * 100)));
    const state = progress >= 100 ? "done" : progress > 8 ? "running" : "queued";
    const updatedJob: MediaGenerationJob = {
      ...job,
      state,
      progress,
      etaMs: Math.max(0, total - elapsed),
      updatedAt: new Date().toISOString(),
    };

    if (state === "done") {
      const resultAsset = buildResultAsset(updatedJob);
      updatedJob.resultAssetId = resultAsset.id;
      return { job: updatedJob, resultAsset };
    }

    return { job: updatedJob };
  }
}
