import type { Asset, DemoState, ExploreProject, Project, StoryStop } from "@/lib/types";

const baseAssets: Asset[] = [
  {
    id: "asset-cover",
    kind: "photo",
    label: "Southwark · Golden Hour",
    title: "Southwark Golden Hour",
    tone: "warm",
    caption: "A cover portrait for the SE1 walks.",
    location: "Southwark, SE1",
    capturedAt: "2025-10-28T17:19:00.000Z",
  },
  {
    id: "asset-market",
    kind: "photo",
    label: "Borough Market · Opening",
    title: "Borough Market at Opening",
    tone: "warm",
    location: "Borough Market, SE1",
    capturedAt: "2025-02-11T07:12:00.000Z",
  },
  {
    id: "asset-shard",
    kind: "photo",
    label: "Crucifix Lane · Glass",
    title: "The Shard from Crucifix Lane",
    tone: "cool",
    location: "Crucifix Lane, SE1",
    capturedAt: "2025-03-07T08:04:00.000Z",
  },
  {
    id: "asset-turbine",
    kind: "photo",
    label: "Tate · Turbine Hall",
    title: "Tate Modern Turbine Hall",
    tone: "punk",
    location: "Tate Modern, SE1",
    capturedAt: "2025-05-19T10:27:00.000Z",
  },
  {
    id: "asset-river",
    kind: "photo",
    label: "South Bank · Mudlark",
    title: "Thames at Low Tide",
    tone: "warm",
    location: "South Bank, SE1",
    capturedAt: "2025-06-20T11:48:00.000Z",
  },
  {
    id: "asset-waterloo",
    kind: "photo",
    label: "Waterloo Bridge · Dusk",
    title: "Waterloo Bridge, Facing East",
    tone: "warm",
    location: "Waterloo Bridge, SE1",
    capturedAt: "2025-10-28T17:19:00.000Z",
  },
  {
    id: "asset-theatre",
    kind: "photo",
    label: "National · Brutalist",
    title: "The National Theatre Facade",
    tone: "cool",
    location: "National Theatre, SE1",
    capturedAt: "2025-11-02T19:02:00.000Z",
  },
  {
    id: "asset-pub",
    kind: "photo",
    label: "Southwark · Pint",
    title: "A Pub off Southwark Street",
    tone: "warm",
    location: "Southwark Street, SE1",
    capturedAt: "2025-12-12T20:15:00.000Z",
  },
  {
    id: "asset-neon",
    kind: "photo",
    label: "Bermondsey Street · Neon",
    title: "Bermondsey Street by Night",
    tone: "punk",
    location: "Bermondsey Street, SE1",
    capturedAt: "2026-01-09T22:40:00.000Z",
  },
  {
    id: "asset-walk-home",
    kind: "photo",
    label: "Grange Road · Streetlight",
    title: "The Walk Home",
    tone: "cool",
    location: "Grange Road, SE1",
    capturedAt: "2026-02-21T23:51:00.000Z",
  },
  {
    id: "asset-tower",
    kind: "photo",
    label: "Tower Bridge · First Light",
    title: "Morning After, Tower Bridge",
    tone: "cool",
    location: "Tower Bridge, SE1",
    capturedAt: "2026-04-14T06:34:00.000Z",
  },
  {
    id: "asset-voice",
    kind: "voice",
    label: "Voice Note 05",
    title: "Waterloo Bridge voice note",
    tone: "neutral",
    transcript:
      "The bridge catches the sun for about six minutes before it tips into the river.",
    location: "Waterloo Bridge",
    capturedAt: "2025-10-28T17:24:00.000Z",
  },
];

const stopSeeds: StoryStop[] = [
  {
    id: "stop-01",
    slug: "borough-market-at-opening",
    number: "01",
    code: "SE1 9DT",
    title: "Borough Market at Opening",
    place: "Borough Market",
    time: "07:12",
    mood: "Amber",
    label: "BOROUGH MKT · MORNING",
    tone: "warm",
    excerpt: "The city is still negotiating with daylight when the shutters come up.",
    story:
      "The market always feels half-private at opening. Forklifts reverse. Coffee arrives before conversation. For ten minutes the arches belong to the people who lift the day into place.",
    lat: 51.5053,
    lng: -0.0909,
    coverAssetId: "asset-market",
    galleryAssetIds: ["asset-market", "asset-cover"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-01-v1",
        label: "v1 · First pass",
        createdAt: "2026-04-14T09:18:00.000Z",
        note: "Warm grain and market sign held.",
        sourceAssetId: "asset-market",
      },
    ],
    activePostcardVersionId: "pc-01-v1",
  },
  {
    id: "stop-02",
    slug: "the-shard-from-crucifix-lane",
    number: "02",
    code: "SE1 2AA",
    title: "The Shard from Crucifix Lane",
    place: "Crucifix Lane",
    time: "08:04",
    mood: "Steel",
    label: "CRUCIFIX LN · GLASS",
    tone: "cool",
    excerpt: "Glass looks most honest before offices fill with people.",
    story:
      "From the lane the tower is almost too large to read. It behaves like weather. You catch it between brick shoulders and then it is everywhere at once.",
    lat: 51.5043,
    lng: -0.0812,
    coverAssetId: "asset-shard",
    galleryAssetIds: ["asset-shard", "asset-market"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-02-v1",
        label: "v1 · Draft",
        createdAt: "2026-04-14T09:24:00.000Z",
        note: "Cool editorial crop held lines well.",
        sourceAssetId: "asset-shard",
      },
    ],
    activePostcardVersionId: "pc-02-v1",
  },
  {
    id: "stop-03",
    slug: "tate-modern-turbine-hall",
    number: "03",
    code: "SE1 9DA",
    title: "Tate Modern Turbine Hall",
    place: "Tate Modern",
    time: "10:27",
    mood: "Rust",
    label: "TATE · TURBINE HALL",
    tone: "punk",
    excerpt: "Some rooms tell you to lower your voice. This one asks for a bigger life.",
    story:
      "The hall still has industrial arrogance in it. You enter and scale reorganises itself. Every coat becomes a silhouette. Every pause becomes theatre.",
    lat: 51.5076,
    lng: -0.0994,
    coverAssetId: "asset-turbine",
    galleryAssetIds: ["asset-turbine", "asset-river"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-03-v1",
        label: "v1 · Punchy",
        createdAt: "2026-04-14T09:28:00.000Z",
        note: "Kept the black floor and the crowd scale.",
        sourceAssetId: "asset-turbine",
      },
    ],
    activePostcardVersionId: "pc-03-v1",
  },
  {
    id: "stop-04",
    slug: "thames-at-low-tide",
    number: "04",
    code: "SE1 8XX",
    title: "Thames at Low Tide",
    place: "South Bank",
    time: "11:48",
    mood: "Mud",
    label: "SOUTH BANK · MUDLARK",
    tone: "warm",
    excerpt: "At low tide London looks less polished and more truthful.",
    story:
      "The river leaves evidence everywhere when it steps back. Iron, clay, bottle necks, old intentions. The bank is a filing cabinet for the city's bad memory.",
    lat: 51.5072,
    lng: -0.1087,
    coverAssetId: "asset-river",
    galleryAssetIds: ["asset-river", "asset-market"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-04-v1",
        label: "v1 · Mudlight",
        createdAt: "2026-04-14T09:34:00.000Z",
        note: "Held the ochre bank and dull silver water.",
        sourceAssetId: "asset-river",
      },
    ],
    activePostcardVersionId: "pc-04-v1",
  },
  {
    id: "stop-05",
    slug: "waterloo-bridge-facing-east",
    number: "05",
    code: "SE1 7PB",
    title: "Waterloo Bridge, Facing East",
    place: "Waterloo Bridge",
    time: "17:19",
    mood: "Gold",
    label: "WATERLOO BR · DUSK",
    tone: "warm",
    excerpt:
      "The bridge catches the sun for about six minutes before it tips into the river.",
    story:
      "I've walked Waterloo Bridge three dozen times and every time it looks like someone cut a different film from the same reel. People cross it with intent, which is why the slow ones stand out. The river is the only thing in London that tells the time.",
    lat: 51.5070,
    lng: -0.1167,
    coverAssetId: "asset-waterloo",
    galleryAssetIds: ["asset-waterloo", "asset-shard", "asset-voice"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-05-v1",
        label: "v1 · First pass",
        createdAt: "2026-04-14T09:40:00.000Z",
        note: "Basic crop.",
        sourceAssetId: "asset-waterloo",
      },
      {
        id: "pc-05-v2",
        label: "v2 · Tighter crop",
        createdAt: "2026-04-14T09:52:00.000Z",
        note: "Brought St Paul's further into frame.",
        sourceAssetId: "asset-waterloo",
      },
      {
        id: "pc-05-v3",
        label: "v3 · Current",
        createdAt: "2026-04-14T10:07:00.000Z",
        note: "Kept architecture, warmer film grain.",
        sourceAssetId: "asset-waterloo",
      },
    ],
    activePostcardVersionId: "pc-05-v3",
  },
  {
    id: "stop-06",
    slug: "the-national-theatre-facade",
    number: "06",
    code: "SE1 8UP",
    title: "The National Theatre Facade",
    place: "National Theatre",
    time: "19:02",
    mood: "Concrete",
    label: "NATIONAL · BRUTALIST",
    tone: "cool",
    excerpt: "Concrete holds dusk longer than glass does.",
    story:
      "The building doesn't soften, even when the light does. It becomes less severe and more exact. Every stair edge starts performing its own shadow line.",
    lat: 51.5079,
    lng: -0.1142,
    coverAssetId: "asset-theatre",
    galleryAssetIds: ["asset-theatre", "asset-waterloo"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-06-v1",
        label: "v1 · Draft",
        createdAt: "2026-04-14T10:18:00.000Z",
        note: "Brutalist crop with slower contrast.",
        sourceAssetId: "asset-theatre",
      },
    ],
    activePostcardVersionId: "pc-06-v1",
  },
  {
    id: "stop-07",
    slug: "a-pub-off-southwark-street",
    number: "07",
    code: "SE1 9PX",
    title: "A Pub off Southwark Street",
    place: "Southwark Street",
    time: "20:15",
    mood: "Ember",
    label: "SOUTHWARK · PINT",
    tone: "warm",
    excerpt: "Pub light is its own kind of weather system.",
    story:
      "The windows make everybody look more certain than they are. Outside, rain threatens. Inside, the room edits you into a bolder version of yourself.",
    lat: 51.5047,
    lng: -0.0937,
    coverAssetId: "asset-pub",
    galleryAssetIds: ["asset-pub", "asset-market"],
    generatedAssetIds: [],
    postcardVersions: [],
    activePostcardVersionId: "",
  },
  {
    id: "stop-08",
    slug: "bermondsey-street-by-night",
    number: "08",
    code: "SE1 2SD",
    title: "Bermondsey Street by Night",
    place: "Bermondsey Street",
    time: "22:40",
    mood: "Neon",
    label: "BERMONDSEY ST · NEON",
    tone: "punk",
    excerpt: "Night makes this street less boutique and more electric.",
    story:
      "Signs take over after ten. You stop reading fronts as shops and start reading them as masks. Pavement reflections do the rest.",
    lat: 51.4985,
    lng: -0.0829,
    coverAssetId: "asset-neon",
    galleryAssetIds: ["asset-neon", "asset-pub"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-08-v1",
        label: "v1 · Neon cut",
        createdAt: "2026-04-14T10:34:00.000Z",
        note: "Higher contrast, signage preserved.",
        sourceAssetId: "asset-neon",
      },
    ],
    activePostcardVersionId: "pc-08-v1",
  },
  {
    id: "stop-09",
    slug: "the-walk-home",
    number: "09",
    code: "SE1 3UN",
    title: "The Walk Home",
    place: "Grange Road",
    time: "23:51",
    mood: "Blue",
    label: "GRANGE RD · STREETLIGHT",
    tone: "cool",
    excerpt: "Every city walk ends with a smaller walk no one writes down.",
    story:
      "The last stretch is always the most accurate one. Not scenic. Not performative. Just the rhythm of keys, pockets, traffic residue and tired shoes on asphalt.",
    lat: 51.4945,
    lng: -0.0814,
    coverAssetId: "asset-walk-home",
    galleryAssetIds: ["asset-walk-home", "asset-neon"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-09-v1",
        label: "v1 · Streetlight",
        createdAt: "2026-04-14T10:41:00.000Z",
        note: "Held the blue cast and single lamp.",
        sourceAssetId: "asset-walk-home",
      },
    ],
    activePostcardVersionId: "pc-09-v1",
  },
  {
    id: "stop-10",
    slug: "morning-after-tower-bridge",
    number: "10",
    code: "SE1 5EN",
    title: "Morning After, Tower Bridge",
    place: "Tower Bridge",
    time: "06:34",
    mood: "Silver",
    label: "TOWER BR · FIRST LIGHT",
    tone: "cool",
    excerpt: "Morning after is a genre all on its own.",
    story:
      "The bridge looks rinsed clean at first light, as though the night has already been processed out of it. It is the same city, but newly printed.",
    lat: 51.5055,
    lng: -0.0754,
    coverAssetId: "asset-tower",
    galleryAssetIds: ["asset-tower", "asset-waterloo"],
    generatedAssetIds: [],
    postcardVersions: [
      {
        id: "pc-10-v1",
        label: "v1 · Silver pass",
        createdAt: "2026-04-14T10:52:00.000Z",
        note: "Cool highlight and soft grain.",
        sourceAssetId: "asset-tower",
      },
    ],
    activePostcardVersionId: "pc-10-v1",
  },
];

export const seedProject: Project = {
  id: "project-se1",
  authorName: "Ana Ishii",
  authorHandle: "@ana-ishii",
  slug: "a-year-in-se1",
  title: "A Year in SE1",
  subtitle: "Ten walks between Bermondsey and Waterloo, 2025–2026",
  description:
    "Photos, places, and fragments reassembled into a London walk story with three narrative grammars.",
  coverLabel: "SOUTHWARK · GOLDEN HOUR",
  area: "SE1 — Southwark / Bermondsey",
  tags: ["SE1", "Walking", "Thames"],
  publishedAt: "14 APR 2026",
  reads: 2487,
  saves: 214,
  duration: "42 min read",
  defaultMode: "fashion",
  visibility: "public",
  status: "in_progress",
  stopIds: stopSeeds.map((stop) => stop.id),
  uploadAssetIds: baseAssets.map((asset) => asset.id),
};

export const exploreProjects: ExploreProject[] = [
  {
    id: "project-se1",
    title: "A Year in SE1",
    author: "Ana Ishii",
    authorHandle: "@ana-ishii",
    slug: "a-year-in-se1",
    stops: 10,
    mode: "fashion",
    label: "SOUTHWARK · COVER",
    reads: "2.4k",
    borough: "SE1 Southwark",
    tone: "warm",
    summary: "Ten walks between Bermondsey and Waterloo, assembled over a year on foot.",
    lat: 51.507,
    lng: -0.103,
  },
  {
    id: "project-mudlark",
    title: "Mudlark Diaries",
    author: "Ty Okafor",
    authorHandle: "@ty-okafor",
    slug: "mudlark-diaries",
    stops: 14,
    mode: "punk",
    label: "THAMES · FORESHORE",
    reads: "891",
    borough: "SE1 Southwark",
    tone: "punk",
    summary: "A rough-cut walk through low tide finds and river residue.",
    lat: 51.503,
    lng: -0.106,
  },
  {
    id: "project-e8",
    title: "48 Hours in E8",
    author: "Priya Shah",
    authorHandle: "@priya-shah",
    slug: "48-hours-in-e8",
    stops: 8,
    mode: "cinema",
    label: "HACKNEY · NIGHT",
    reads: "4.1k",
    borough: "E8 Hackney",
    tone: "dark",
    summary: "Two sleepless days staged like a low-budget film.",
    lat: 51.546,
    lng: -0.075,
  },
  {
    id: "project-jubilee",
    title: "The Jubilee Walk",
    author: "Lena Park",
    authorHandle: "@lena-park",
    slug: "the-jubilee-walk",
    stops: 12,
    mode: "fashion",
    label: "WESTMINSTER · DAY",
    reads: "1.2k",
    borough: "SW1 Westminster",
    tone: "warm",
    summary: "River landmarks rendered as a polished editorial essay.",
    lat: 51.5007,
    lng: -0.1246,
  },
  {
    id: "project-last-trains",
    title: "Last Trains",
    author: "Marco Reed",
    authorHandle: "@marco-reed",
    slug: "last-trains",
    stops: 7,
    mode: "cinema",
    label: "UNDERGROUND · 00:47",
    reads: "3.6k",
    borough: "W1 Soho / Fitzrovia",
    tone: "dark",
    summary: "A night transport diary told as scene cards and subtitles.",
    lat: 51.515,
    lng: -0.141,
  },
  {
    id: "project-brick-lane",
    title: "Brick Lane after rain",
    author: "Yui Tanaka",
    authorHandle: "@yui-tanaka",
    slug: "brick-lane-after-rain",
    stops: 9,
    mode: "punk",
    label: "E1 · WET ASPHALT",
    reads: "624",
    borough: "E1 Whitechapel",
    tone: "punk",
    summary: "Stickered shutters, wet signs and a camera that stays too close.",
    lat: 51.521,
    lng: -0.071,
  },
];

export const seedState: DemoState = {
  currentMode: "fashion",
  activeProjectId: seedProject.id,
  projects: [seedProject],
  stops: stopSeeds,
  assets: baseAssets,
  mediaJobs: [
    {
      id: "job-seed-01",
      projectId: seedProject.id,
      stopId: "stop-05",
      sourceAssetId: "asset-waterloo",
      resultAssetId: "generated-job-seed-01",
      kind: "image-to-image",
      state: "done",
      prompt: "golden-hour editorial, keep architecture, slight film grain",
      strength: 0.62,
      seed: 184302,
      progress: 100,
      etaMs: 0,
      createdAt: "2026-04-14T10:09:00.000Z",
      updatedAt: "2026-04-14T10:09:03.000Z",
      provider: "mock-media-provider",
    },
    {
      id: "job-seed-02",
      projectId: seedProject.id,
      stopId: "stop-08",
      sourceAssetId: "asset-neon",
      kind: "image-to-video",
      state: "running",
      prompt: "animate a slow neon sweep with wet reflections",
      strength: 0.7,
      seed: 947113,
      progress: 58,
      etaMs: 18000,
      createdAt: "2026-04-18T15:58:00.000Z",
      updatedAt: "2026-04-18T16:00:00.000Z",
      provider: "mock-media-provider",
    },
  ],
};

seedState.assets.push({
  id: "generated-job-seed-01",
  kind: "generated-image",
  label: "IMG2IMG · Waterloo v3",
  title: "Waterloo Bridge editorial pass",
  tone: "warm",
  caption: "Mock provider result for stop 05.",
  notes: "Result saved from the mock media provider.",
});

export function getProjectBySlug(authorHandle: string, slug: string, projects: Project[]) {
  return projects.find(
    (project) => project.authorHandle === authorHandle && project.slug === slug,
  );
}

export function getStopBySlug(slug: string, stops: StoryStop[]) {
  return stops.find((stop) => stop.slug === slug);
}
